export type MachineCategory = 'piernas' | 'torso' | 'brazos' | 'core' | 'multifuncional' | 'cardio';

export interface GymMachine {
  id: string;
  machineNumber?: string;
  name: string;
  alias: string;
  images: [string, string];
  category: MachineCategory;
  muscles: string[];
  description: string;
}

const machineImagePair = (exerciseId: string): [string, string] => [
  `/images/exercises/machines/${exerciseId}-inicio.jpg`,
  `/images/exercises/machines/${exerciseId}-final.jpg`,
];

export const MACHINE_CATEGORY_LABELS: Record<MachineCategory, string> = {
  piernas: 'Piernas y glúteos',
  torso: 'Pecho y espalda',
  brazos: 'Hombros y brazos',
  core: 'Abdomen y lumbar',
  multifuncional: 'Multifuncionales',
  cardio: 'Cardio',
};

export const SMARTFIT_MACHINES: GymMachine[] = [
  {
    id: 'leg-press-horizontal',
    machineNumber: '01',
    name: 'Leg press horizontal',
    alias: 'Prensa horizontal de piernas',
    images: machineImagePair('leg-press-horizontal'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    description: 'Empuja la plataforma al frente con una trayectoria guiada y estable.',
  },
  {
    id: 'leg-extension',
    machineNumber: '02',
    name: 'Leg extension',
    alias: 'Extensión de piernas',
    images: machineImagePair('leg-extension'),
    category: 'piernas',
    muscles: ['Cuádriceps'],
    description: 'Aísla el cuádriceps al extender las rodillas desde una posición sentada.',
  },
  {
    id: 'leg-curl-acostado',
    machineNumber: '03',
    name: 'Leg curl acostado',
    alias: 'Curl femoral acostado',
    images: machineImagePair('leg-curl-acostado'),
    category: 'piernas',
    muscles: ['Isquiotibiales', 'Pantorrillas'],
    description: 'Trabaja la parte posterior del muslo flexionando las rodillas boca abajo.',
  },
  {
    id: 'seated-leg-curl',
    machineNumber: '04',
    name: 'Seated leg curl',
    alias: 'Curl femoral sentado',
    images: machineImagePair('seated-leg-curl'),
    category: 'piernas',
    muscles: ['Isquiotibiales', 'Pantorrillas'],
    description: 'Flexiona las rodillas desde el asiento para aislar los isquiotibiales.',
  },
  {
    id: 'hip-abduction',
    machineNumber: '05',
    name: 'Hip abduction',
    alias: 'Abducción de cadera',
    images: machineImagePair('hip-abduction'),
    category: 'piernas',
    muscles: ['Glúteo medio', 'Glúteo menor', 'Abductores'],
    description: 'Abre las piernas contra la resistencia para fortalecer la cadera exterior.',
  },
  {
    id: 'hip-adduction',
    machineNumber: '06',
    name: 'Hip adduction',
    alias: 'Aducción de cadera',
    images: machineImagePair('hip-adduction'),
    category: 'piernas',
    muscles: ['Aductores', 'Muslo interno'],
    description: 'Cierra las piernas contra la resistencia para trabajar el muslo interno.',
  },
  {
    id: 'hip-and-glute',
    machineNumber: '07',
    name: 'Hip and glute',
    alias: 'Máquina de glúteo y cadera',
    images: machineImagePair('hip-and-glute'),
    category: 'piernas',
    muscles: ['Glúteo mayor', 'Isquiotibiales'],
    description: 'Realiza una extensión controlada de cadera para enfatizar los glúteos.',
  },
  {
    id: 'calf',
    machineNumber: '08',
    name: 'Calf',
    alias: 'Elevación de talones',
    images: machineImagePair('calf'),
    category: 'piernas',
    muscles: ['Gastrocnemio', 'Sóleo'],
    description: 'Extiende los tobillos para entrenar las pantorrillas de forma guiada.',
  },
  {
    id: 'leg-press-45',
    machineNumber: '09',
    name: 'Leg press 45°',
    alias: 'Prensa inclinada de peso libre',
    images: machineImagePair('leg-press-45'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    description: 'Desplaza una plataforma inclinada cargada con discos usando ambas piernas.',
  },
  {
    id: 'hack-squat',
    machineNumber: '10',
    name: 'Linear hack',
    alias: 'Hack squat',
    images: machineImagePair('hack-squat'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Aductores'],
    description: 'Simula una sentadilla inclinada con espalda apoyada y recorrido guiado.',
  },
  {
    id: 'chest-press',
    machineNumber: '20',
    name: 'Chest press',
    alias: 'Prensa de pecho',
    images: machineImagePair('chest-press'),
    category: 'torso',
    muscles: ['Pectorales', 'Tríceps', 'Deltoide anterior'],
    description: 'Empuja al frente desde el asiento para entrenar el pecho con apoyo estable.',
  },
  {
    id: 'rear-delt',
    machineNumber: '21',
    name: 'Rear delt',
    alias: 'Vuelo inverso',
    images: machineImagePair('rear-delt'),
    category: 'torso',
    muscles: ['Deltoide posterior', 'Romboides', 'Trapecio'],
    description: 'Abre los brazos hacia atrás para fortalecer hombros posteriores y espalda alta.',
  },
  {
    id: 'pectoral-fly',
    machineNumber: '21',
    name: 'Pectoral fly',
    alias: 'Pec fly',
    images: machineImagePair('pectoral-fly'),
    category: 'torso',
    muscles: ['Pectorales', 'Deltoide anterior'],
    description: 'Junta los brazos al frente manteniendo una tensión constante sobre el pecho.',
  },
  {
    id: 'lat-pulldown',
    machineNumber: '22',
    name: 'Lat pulldown',
    alias: 'Jalón al pecho',
    images: machineImagePair('lat-pulldown'),
    category: 'torso',
    muscles: ['Dorsales', 'Bíceps', 'Redondo mayor'],
    description: 'Lleva las empuñaduras hacia el pecho para desarrollar la amplitud de la espalda.',
  },
  {
    id: 'row',
    machineNumber: '23',
    name: 'Row',
    alias: 'Remo sentado',
    images: machineImagePair('row'),
    category: 'torso',
    muscles: ['Dorsales', 'Romboides', 'Bíceps'],
    description: 'Tira de las empuñaduras hacia el torso para trabajar la espalda media.',
  },
  {
    id: 'remo-sentado-upform',
    name: 'Remo sentado con apoyo torácico',
    alias: 'UpForm UR-U032 2.0',
    images: machineImagePair('remo-sentado-upform'),
    category: 'torso',
    muscles: ['Dorsales', 'Romboides', 'Trapecio', 'Bíceps'],
    description:
      'Jala las empuñaduras hacia el torso manteniendo el pecho apoyado y los hombros controlados.',
  },
  {
    id: 'fly',
    machineNumber: '24',
    name: 'Fly',
    alias: 'Vuelo para pecho',
    images: machineImagePair('fly'),
    category: 'torso',
    muscles: ['Pectorales', 'Deltoide anterior'],
    description: 'Realiza un movimiento de abrazo para aislar los músculos pectorales.',
  },
  {
    id: 'pulldown',
    machineNumber: '33',
    name: 'Pulldown',
    alias: 'Jalón guiado',
    images: machineImagePair('pulldown'),
    category: 'torso',
    muscles: ['Dorsales', 'Bíceps', 'Trapecio inferior'],
    description:
      'Jala las palancas desde arriba en una trayectoria estable para entrenar dorsales.',
  },
  {
    id: 'abdominal-crunch',
    machineNumber: '40',
    name: 'Abdominal',
    alias: 'Crunch machine',
    images: machineImagePair('abdominal-crunch'),
    category: 'core',
    muscles: ['Recto abdominal', 'Oblicuos'],
    description: 'Flexiona el torso contra la resistencia para aislar la zona abdominal.',
  },
  {
    id: 'mts-abdominal',
    machineNumber: '41',
    name: 'MTS Abdominal',
    alias: 'Crunch abdominal MTS',
    images: machineImagePair('mts-abdominal'),
    category: 'core',
    muscles: ['Recto abdominal', 'Oblicuos'],
    description: 'Permite una contracción abdominal independiente con carga en ambos lados.',
  },
  {
    id: 'back-extension',
    machineNumber: '42',
    name: 'Back extension',
    alias: 'Extensión lumbar',
    images: machineImagePair('back-extension'),
    category: 'core',
    muscles: ['Erectores espinales', 'Glúteos'],
    description: 'Extiende el torso de forma controlada para fortalecer la zona lumbar.',
  },
  {
    id: 'shoulder-press',
    machineNumber: '50',
    name: 'Shoulder press',
    alias: 'Press de hombros',
    images: machineImagePair('shoulder-press'),
    category: 'brazos',
    muscles: ['Deltoides', 'Tríceps'],
    description: 'Empuja sobre la cabeza con apoyo lumbar para entrenar los hombros.',
  },
  {
    id: 'triceps-press',
    machineNumber: '51',
    name: 'Triceps press',
    alias: 'Extensión de tríceps',
    images: machineImagePair('triceps-press'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description:
      'Extiende los codos contra la resistencia para aislar la parte posterior del brazo.',
  },
  {
    id: 'biceps-curl',
    machineNumber: '52',
    name: 'Biceps curl',
    alias: 'Curl de bíceps',
    images: machineImagePair('biceps-curl'),
    category: 'brazos',
    muscles: ['Bíceps', 'Braquial'],
    description:
      'Flexiona los codos con los brazos apoyados para concentrar el trabajo en el bíceps.',
  },
  {
    id: 'smith',
    machineNumber: '60',
    name: 'Smith',
    alias: 'Máquina Smith',
    images: machineImagePair('smith'),
    category: 'multifuncional',
    muscles: ['Piernas', 'Glúteos', 'Pecho', 'Hombros'],
    description: 'Barra guiada para sentadillas, presses y otros ejercicios con peso libre.',
  },
  {
    id: 'assisted-dip-chin',
    machineNumber: '61',
    name: 'Assisted dip/chin',
    alias: 'Dominadas y fondos asistidos',
    images: machineImagePair('assisted-dip-chin'),
    category: 'multifuncional',
    muscles: ['Dorsales', 'Bíceps', 'Pectorales', 'Tríceps'],
    description: 'El contrapeso facilita dominadas y fondos mientras desarrollas fuerza.',
  },
  {
    id: 'dual-cable-cross',
    machineNumber: '62',
    name: 'Dual cable cross',
    alias: 'Polea doble ajustable',
    images: machineImagePair('dual-cable-cross'),
    category: 'multifuncional',
    muscles: ['Cuerpo completo'],
    description: 'Dos poleas regulables permiten empujes, jalones, curls y extensiones.',
  },
  {
    id: 'cable-crossover',
    machineNumber: '63',
    name: 'Cable crossover',
    alias: 'Cruce de poleas',
    images: machineImagePair('cable-crossover'),
    category: 'multifuncional',
    muscles: ['Pecho', 'Espalda', 'Hombros', 'Brazos', 'Glúteos'],
    description: 'Estación amplia de cables para entrenar distintos patrones y grupos musculares.',
  },
  {
    id: 'caminadora',
    name: 'Caminadora',
    alias: 'Treadmill',
    images: machineImagePair('caminadora'),
    category: 'cardio',
    muscles: ['Piernas', 'Glúteos', 'Sistema cardiovascular'],
    description: 'Permite caminar o correr ajustando velocidad e inclinación.',
  },
  {
    id: 'bicicleta-ergometrica',
    name: 'Bicicleta ergométrica',
    alias: 'Bicicleta vertical',
    images: machineImagePair('bicicleta-ergometrica'),
    category: 'cardio',
    muscles: ['Cuádriceps', 'Glúteos', 'Pantorrillas'],
    description: 'Cardio de bajo impacto con resistencia regulable desde el panel.',
  },
  {
    id: 'eliptica',
    name: 'Elíptica',
    alias: 'Cross-trainer',
    images: machineImagePair('eliptica'),
    category: 'cardio',
    muscles: ['Piernas', 'Glúteos', 'Brazos'],
    description: 'Movimiento continuo de cuerpo completo con bajo impacto articular.',
  },
  {
    id: 'remo-indoor',
    name: 'Remo indoor',
    alias: 'Remo ergométrico',
    images: machineImagePair('remo-indoor'),
    category: 'cardio',
    muscles: ['Espalda', 'Piernas', 'Core', 'Brazos'],
    description:
      'Combina empuje de piernas y jalón del torso en un ejercicio cardiovascular completo.',
  },
];
