import type { ExerciseTracking } from '@/types/exercise.types';

export type MachineCategory = 'piernas' | 'torso' | 'brazos' | 'core' | 'multifuncional' | 'cardio';

export interface GymMachine {
  id: string;
  machineNumber?: string;
  name: string;
  alias: string;
  images: [string, string];
  category: MachineCategory;
  /** Músculo principal primero; los demás son secundarios. */
  muscles: string[];
  description: string;
  /** Cómo se registra el progreso. Ausente equivale a `weight`. */
  tracking?: ExerciseTracking;
}

const machineImagePair = (exerciseId: string): [string, string] => [
  `/images/exercises/machines/${exerciseId}-inicio.jpg`,
  `/images/exercises/machines/${exerciseId}-final.jpg`,
];

export const MACHINE_CATEGORY_LABELS: Record<MachineCategory, string> = {
  piernas: 'Piernas y glúteos',
  torso: 'Pecho y espalda',
  brazos: 'Hombros y brazos',
  core: 'Abdomen y lumbar',
  multifuncional: 'Multifuncionales',
  cardio: 'Cardio',
};

export const SMARTFIT_MACHINES: GymMachine[] = [
  {
    id: 'leg-press-horizontal',
    machineNumber: '01',
    name: 'Leg press horizontal',
    alias: 'Prensa horizontal de piernas',
    images: machineImagePair('leg-press-horizontal'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    description: 'Empuja la plataforma al frente con una trayectoria guiada y estable.',
  },
  {
    id: 'leg-extension',
    machineNumber: '02',
    name: 'Leg extension',
    alias: 'Extensión de piernas',
    images: machineImagePair('leg-extension'),
    category: 'piernas',
    muscles: ['Cuádriceps'],
    description: 'Aísla el cuádriceps al extender las rodillas desde una posición sentada.',
  },
  {
    id: 'leg-curl-acostado',
    machineNumber: '03',
    name: 'Leg curl acostado',
    alias: 'Curl femoral acostado',
    images: machineImagePair('leg-curl-acostado'),
    category: 'piernas',
    muscles: ['Isquiotibiales', 'Pantorrillas'],
    description: 'Trabaja la parte posterior del muslo flexionando las rodillas boca abajo.',
  },
  {
    id: 'seated-leg-curl',
    machineNumber: '04',
    name: 'Seated leg curl',
    alias: 'Curl femoral sentado',
    images: machineImagePair('seated-leg-curl'),
    category: 'piernas',
    muscles: ['Isquiotibiales', 'Pantorrillas'],
    description: 'Flexiona las rodillas desde el asiento para aislar los isquiotibiales.',
  },
  {
    id: 'curl-femoral-pie-maquina',
    name: 'Curl femoral de pie',
    alias: 'Standing leg curl machine',
    images: machineImagePair('curl-femoral-pie-maquina'),
    category: 'piernas',
    muscles: ['Isquiotibiales'],
    description: 'Flexiona una rodilla a la vez manteniendo la cadera apoyada y estable.',
  },
  {
    id: 'hip-abduction',
    machineNumber: '05',
    name: 'Hip abduction',
    alias: 'Abducción de cadera',
    images: machineImagePair('hip-abduction'),
    category: 'piernas',
    muscles: ['Glúteo medio', 'Glúteo menor', 'Abductores'],
    description: 'Abre las piernas contra la resistencia para fortalecer la cadera exterior.',
  },
  {
    id: 'hip-adduction',
    machineNumber: '06',
    name: 'Hip adduction',
    alias: 'Aducción de cadera',
    images: machineImagePair('hip-adduction'),
    category: 'piernas',
    muscles: ['Aductores', 'Muslo interno'],
    description: 'Cierra las piernas contra la resistencia para trabajar el muslo interno.',
  },
  {
    id: 'hip-and-glute',
    machineNumber: '07',
    name: 'Hip and glute',
    alias: 'Máquina de glúteo y cadera',
    images: machineImagePair('hip-and-glute'),
    category: 'piernas',
    muscles: ['Glúteo mayor', 'Isquiotibiales'],
    description: 'Realiza una extensión controlada de cadera para enfatizar los glúteos.',
  },
  {
    id: 'patada-gluteo-polea',
    name: 'Patada de glúteo en polea',
    alias: 'Cable glute kickback',
    images: machineImagePair('patada-gluteo-polea'),
    category: 'piernas',
    muscles: ['Glúteo mayor', 'Isquiotibiales'],
    description: 'Extiende una pierna hacia atrás con tobillera sin arquear la zona lumbar.',
  },
  {
    id: 'calf',
    machineNumber: '08',
    name: 'Calf',
    alias: 'Elevación de talones',
    images: machineImagePair('calf'),
    category: 'piernas',
    muscles: ['Gastrocnemio', 'Sóleo'],
    description: 'Extiende los tobillos para entrenar las pantorrillas de forma guiada.',
  },
  {
    id: 'pantorrilla-sentada-maquina',
    name: 'Elevación de pantorrilla sentada',
    alias: 'Seated calf raise machine',
    images: machineImagePair('pantorrilla-sentada-maquina'),
    category: 'piernas',
    muscles: ['Sóleo', 'Gastrocnemio'],
    description: 'Eleva los talones con las rodillas flexionadas para priorizar el sóleo.',
  },
  {
    id: 'leg-press-45',
    machineNumber: '09',
    name: 'Leg press 45°',
    alias: 'Prensa inclinada de peso libre',
    images: machineImagePair('leg-press-45'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    description: 'Desplaza una plataforma inclinada cargada con discos usando ambas piernas.',
  },
  {
    id: 'hack-squat',
    machineNumber: '10',
    name: 'Linear hack',
    alias: 'Hack squat',
    images: machineImagePair('hack-squat'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Aductores'],
    description: 'Simula una sentadilla inclinada con espalda apoyada y recorrido guiado.',
  },
  {
    id: 'chest-press',
    machineNumber: '20',
    name: 'Chest press',
    alias: 'Prensa de pecho',
    images: machineImagePair('chest-press'),
    category: 'torso',
    muscles: ['Pectorales', 'Tríceps', 'Deltoide anterior'],
    description: 'Empuja al frente desde el asiento para entrenar el pecho con apoyo estable.',
  },
  {
    id: 'press-inclinado-maquina',
    name: 'Press inclinado en máquina',
    alias: 'Leverage incline chest press',
    images: machineImagePair('press-inclinado-maquina'),
    category: 'torso',
    muscles: ['Pectoral superior', 'Deltoide anterior', 'Tríceps'],
    description: 'Empuja las palancas hacia arriba para priorizar la parte superior del pecho.',
  },
  {
    id: 'press-declinado-maquina',
    name: 'Press declinado en máquina',
    alias: 'Leverage decline chest press',
    images: machineImagePair('press-declinado-maquina'),
    category: 'torso',
    muscles: ['Pectoral inferior', 'Tríceps', 'Deltoide anterior'],
    description: 'Empuja las palancas en trayectoria descendente con la espalda apoyada.',
  },
  {
    id: 'press-banca-barra',
    name: 'Press de banca con barra',
    alias: 'Barbell bench press',
    images: machineImagePair('press-banca-barra'),
    category: 'torso',
    muscles: ['Pectoral mayor', 'Tríceps', 'Deltoide anterior'],
    description: 'Empuja la barra desde el pecho en un banco plano con los pies firmes.',
  },
  {
    id: 'press-inclinado-barra',
    name: 'Press inclinado con barra',
    alias: 'Incline barbell bench press',
    images: machineImagePair('press-inclinado-barra'),
    category: 'torso',
    muscles: ['Pectoral superior', 'Tríceps', 'Deltoide anterior'],
    description: 'Empuja la barra desde un banco inclinado para priorizar la parte alta del pecho.',
  },
  {
    id: 'rear-delt',
    machineNumber: '21',
    name: 'Rear delt',
    alias: 'Vuelo inverso',
    images: machineImagePair('rear-delt'),
    category: 'torso',
    muscles: ['Deltoide posterior', 'Romboides', 'Trapecio'],
    description: 'Abre los brazos hacia atrás para fortalecer hombros posteriores y espalda alta.',
  },
  {
    id: 'pectoral-fly',
    machineNumber: '21',
    name: 'Pectoral fly',
    alias: 'Pec fly',
    images: machineImagePair('pectoral-fly'),
    category: 'torso',
    muscles: ['Pectorales', 'Deltoide anterior'],
    description: 'Junta los brazos al frente manteniendo una tensión constante sobre el pecho.',
  },
  {
    id: 'lat-pulldown',
    machineNumber: '22',
    name: 'Lat pulldown',
    alias: 'Jalón al pecho',
    images: machineImagePair('lat-pulldown'),
    category: 'torso',
    muscles: ['Dorsales', 'Bíceps', 'Redondo mayor'],
    description: 'Lleva las empuñaduras hacia el pecho para desarrollar la amplitud de la espalda.',
  },
  {
    id: 'row',
    machineNumber: '23',
    name: 'Row',
    alias: 'Remo sentado',
    images: machineImagePair('row'),
    category: 'torso',
    muscles: ['Dorsales', 'Romboides', 'Bíceps'],
    description: 'Tira de las empuñaduras hacia el torso para trabajar la espalda media.',
  },
  {
    id: 'remo-sentado-upform',
    name: 'Remo sentado con apoyo torácico',
    alias: 'UpForm UR-U032 2.0',
    images: machineImagePair('remo-sentado-upform'),
    category: 'torso',
    muscles: ['Dorsales', 'Romboides', 'Trapecio', 'Bíceps'],
    description:
      'Jala las empuñaduras hacia el torso manteniendo el pecho apoyado y los hombros controlados.',
  },
  {
    id: 'remo-alto-maquina',
    name: 'Remo alto en máquina',
    alias: 'Leverage high row',
    images: machineImagePair('remo-alto-maquina'),
    category: 'torso',
    muscles: ['Espalda media', 'Dorsales', 'Romboides'],
    description: 'Jala las palancas desde arriba hacia el torso manteniendo el pecho estable.',
  },
  {
    id: 'fly',
    machineNumber: '24',
    name: 'Fly',
    alias: 'Vuelo para pecho',
    images: machineImagePair('fly'),
    category: 'torso',
    muscles: ['Pectorales', 'Deltoide anterior'],
    description: 'Realiza un movimiento de abrazo para aislar los músculos pectorales.',
  },
  {
    id: 'pulldown',
    machineNumber: '33',
    name: 'Pulldown',
    alias: 'Jalón guiado',
    images: machineImagePair('pulldown'),
    category: 'torso',
    muscles: ['Dorsales', 'Bíceps', 'Trapecio inferior'],
    description:
      'Jala las palancas desde arriba en una trayectoria estable para entrenar dorsales.',
  },
  {
    id: 'pullover-polea-cuerda',
    name: 'Pullover en polea con cuerda',
    alias: 'Straight-arm cable pulldown',
    images: machineImagePair('pullover-polea-cuerda'),
    category: 'torso',
    muscles: ['Dorsales'],
    description: 'Baja la cuerda con los brazos casi extendidos sin convertirlo en un remo.',
  },
  {
    id: 'abdominal-crunch',
    machineNumber: '40',
    name: 'Abdominal',
    alias: 'Crunch machine',
    images: machineImagePair('abdominal-crunch'),
    category: 'core',
    muscles: ['Recto abdominal', 'Oblicuos'],
    description: 'Flexiona el torso contra la resistencia para aislar la zona abdominal.',
  },
  {
    id: 'mts-abdominal',
    machineNumber: '41',
    name: 'MTS Abdominal',
    alias: 'Crunch abdominal MTS',
    images: machineImagePair('mts-abdominal'),
    category: 'core',
    muscles: ['Recto abdominal', 'Oblicuos'],
    description: 'Permite una contracción abdominal independiente con carga en ambos lados.',
  },
  {
    id: 'crunch-polea',
    name: 'Crunch en polea',
    alias: 'Kneeling cable crunch',
    images: machineImagePair('crunch-polea'),
    category: 'core',
    muscles: ['Recto abdominal'],
    description: 'Flexiona el tronco de rodillas llevando las costillas hacia la pelvis.',
  },
  {
    id: 'woodchop-polea',
    name: 'Woodchop en polea',
    alias: 'Standing cable wood chop',
    images: machineImagePair('woodchop-polea'),
    category: 'core',
    muscles: ['Oblicuos', 'Recto abdominal'],
    description: 'Gira el tronco en diagonal manteniendo caderas y columna bajo control.',
  },
  {
    id: 'back-extension',
    machineNumber: '42',
    name: 'Back extension',
    alias: 'Extensión lumbar',
    images: machineImagePair('back-extension'),
    category: 'core',
    muscles: ['Erectores espinales', 'Glúteos'],
    description: 'Extiende el torso de forma controlada para fortalecer la zona lumbar.',
    tracking: 'reps',
  },
  {
    id: 'shoulder-press',
    machineNumber: '50',
    name: 'Shoulder press',
    alias: 'Press de hombros',
    images: machineImagePair('shoulder-press'),
    category: 'brazos',
    muscles: ['Deltoides', 'Tríceps'],
    description: 'Empuja sobre la cabeza con apoyo lumbar para entrenar los hombros.',
  },
  {
    id: 'elevacion-lateral-polea',
    name: 'Elevación lateral en polea',
    alias: 'Low-pulley deltoid raise',
    images: machineImagePair('elevacion-lateral-polea'),
    category: 'brazos',
    muscles: ['Deltoide lateral', 'Antebrazos'],
    description: 'Eleva el brazo hacia el costado contra la tensión continua de la polea baja.',
  },
  {
    id: 'remo-deltoide-posterior-polea',
    name: 'Remo para deltoide posterior en polea',
    alias: 'Cable rope rear-delt row',
    images: machineImagePair('remo-deltoide-posterior-polea'),
    category: 'brazos',
    muscles: ['Deltoide posterior', 'Romboides', 'Bíceps'],
    description: 'Lleva la cuerda hacia el rostro con los codos altos y hombros controlados.',
  },
  {
    id: 'triceps-press',
    machineNumber: '51',
    name: 'Triceps press',
    alias: 'Extensión de tríceps',
    images: machineImagePair('triceps-press'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description:
      'Extiende los codos contra la resistencia para aislar la parte posterior del brazo.',
  },
  {
    id: 'pushdown-triceps-cuerda',
    name: 'Pushdown de tríceps con cuerda',
    alias: 'Rope triceps pushdown',
    images: machineImagePair('pushdown-triceps-cuerda'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description: 'Extiende los codos junto al cuerpo y separa la cuerda al final del recorrido.',
  },
  {
    id: 'extension-triceps-cabeza-polea',
    name: 'Extensión de tríceps sobre la cabeza',
    alias: 'Overhead rope triceps extension',
    images: machineImagePair('extension-triceps-cabeza-polea'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description: 'Extiende los codos con la cuerda detrás de la cabeza sin abrirlos en exceso.',
  },
  {
    id: 'fondos-maquina',
    name: 'Fondos en máquina',
    alias: 'Dip machine',
    images: machineImagePair('fondos-maquina'),
    category: 'brazos',
    muscles: ['Tríceps', 'Pectorales', 'Deltoide anterior'],
    description: 'Empuja las palancas hacia abajo manteniendo los codos cerca del torso.',
  },
  {
    id: 'biceps-curl',
    machineNumber: '52',
    name: 'Biceps curl',
    alias: 'Curl de bíceps',
    images: machineImagePair('biceps-curl'),
    category: 'brazos',
    muscles: ['Bíceps', 'Braquial'],
    description:
      'Flexiona los codos con los brazos apoyados para concentrar el trabajo en el bíceps.',
  },
  {
    id: 'curl-biceps-polea',
    name: 'Curl de bíceps en polea',
    alias: 'Standing cable curl',
    images: machineImagePair('curl-biceps-polea'),
    category: 'brazos',
    muscles: ['Bíceps'],
    description: 'Flexiona los codos desde la polea baja sin balancear el torso.',
  },
  {
    id: 'curl-martillo-polea',
    name: 'Curl martillo con cuerda',
    alias: 'Cable rope hammer curl',
    images: machineImagePair('curl-martillo-polea'),
    category: 'brazos',
    muscles: ['Bíceps', 'Braquial', 'Braquiorradial'],
    description: 'Flexiona los codos con agarre neutro y las puntas de la cuerda separadas.',
  },
  {
    id: 'curl-muneca-polea',
    name: 'Curl de muñeca en polea',
    alias: 'Cable wrist curl',
    images: machineImagePair('curl-muneca-polea'),
    category: 'brazos',
    muscles: ['Antebrazos'],
    description: 'Flexiona únicamente las muñecas apoyando los antebrazos sobre los muslos.',
  },
  {
    id: 'encogimiento-polea',
    name: 'Encogimiento en polea',
    alias: 'Cable shrug',
    images: machineImagePair('encogimiento-polea'),
    category: 'brazos',
    muscles: ['Trapecio superior'],
    description: 'Eleva los hombros verticalmente con los brazos extendidos y sin girarlos.',
  },
  {
    id: 'rompecraneos-barra-z',
    name: 'Rompecráneos con barra Z',
    alias: 'EZ-bar skullcrusher',
    images: machineImagePair('rompecraneos-barra-z'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description:
      'Acostado en el banco, baja la barra Z hacia la frente flexionando solo los codos y extiende sin mover los hombros.',
  },
  {
    id: 'press-frances-sentado',
    name: 'Press francés sentado con barra Z',
    alias: 'Seated EZ-bar french press',
    images: machineImagePair('press-frances-sentado'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description:
      'Sentado, baja la barra Z por detrás de la cabeza y extiende los codos manteniéndolos cerca.',
  },
  {
    id: 'fondos-en-banco',
    name: 'Fondos en banco',
    alias: 'Bench dips',
    images: machineImagePair('fondos-en-banco'),
    category: 'brazos',
    muscles: ['Tríceps', 'Deltoide anterior', 'Pectorales'],
    description:
      'Con las manos en el borde del banco, baja el cuerpo flexionando los codos y empuja hasta extenderlos.',
    tracking: 'reps',
  },
  {
    id: 'fondos-en-paralelas',
    name: 'Fondos en paralelas',
    alias: 'Parallel bar dip',
    images: machineImagePair('fondos-en-paralelas'),
    category: 'brazos',
    muscles: ['Tríceps', 'Pectoral inferior', 'Deltoide anterior'],
    description:
      'Sostén el cuerpo en las barras, baja con el torso vertical y empuja hasta extender los codos.',
    tracking: 'reps',
  },
  {
    id: 'pushdown-barra-v',
    name: 'Pushdown de tríceps con barra V',
    alias: 'V-bar triceps pushdown',
    images: machineImagePair('pushdown-barra-v'),
    category: 'brazos',
    muscles: ['Tríceps'],
    description:
      'Extiende los codos empujando la barra V hacia abajo con los brazos junto al torso.',
  },
  {
    id: 'curl-barra-z',
    name: 'Curl con barra Z',
    alias: 'EZ-bar curl',
    images: machineImagePair('curl-barra-z'),
    category: 'brazos',
    muscles: ['Bíceps braquial', 'Braquiorradial'],
    description:
      'Flexiona los codos con la barra Z sin balancear el torso; el agarre inclinado cuida las muñecas.',
  },
  {
    id: 'curl-barra-recta',
    name: 'Curl con barra recta',
    alias: 'Barbell curl',
    images: machineImagePair('curl-barra-recta'),
    category: 'brazos',
    muscles: ['Bíceps braquial', 'Braquial anterior'],
    description:
      'Sube la barra flexionando los codos con los brazos pegados al torso y sin impulso.',
  },
  {
    id: 'curl-predicador',
    name: 'Curl en banco predicador',
    alias: 'Preacher curl',
    images: machineImagePair('curl-predicador'),
    category: 'brazos',
    muscles: ['Bíceps braquial'],
    description:
      'Con los brazos apoyados en el atril inclinado, flexiona los codos sin despegar los tríceps.',
  },
  {
    id: 'curl-arana',
    name: 'Curl araña',
    alias: 'Spider curl',
    images: machineImagePair('curl-arana'),
    category: 'brazos',
    muscles: ['Bíceps braquial'],
    description:
      'Boca abajo sobre el banco inclinado, sube la barra con los brazos colgando en vertical.',
  },
  {
    id: 'curl-invertido',
    name: 'Curl invertido con barra',
    alias: 'Reverse barbell curl',
    images: machineImagePair('curl-invertido'),
    category: 'brazos',
    muscles: ['Braquiorradial', 'Bíceps braquial', 'Antebrazos'],
    description:
      'Toma la barra con las palmas hacia abajo y flexiona los codos para cargar el antebrazo.',
  },
  {
    id: 'press-militar-barra',
    name: 'Press militar con barra',
    alias: 'Standing military press',
    images: machineImagePair('press-militar-barra'),
    category: 'brazos',
    muscles: ['Deltoide anterior', 'Deltoide lateral', 'Tríceps'],
    description:
      'De pie, empuja la barra desde los hombros hasta arriba con el core firme y sin arquear la espalda.',
  },
  {
    id: 'face-pull',
    name: 'Face pull con cuerda',
    alias: 'Face pull',
    images: machineImagePair('face-pull'),
    category: 'brazos',
    muscles: ['Deltoide posterior', 'Trapecio', 'Romboides'],
    description:
      'Jala la cuerda hacia la cara con los codos altos y abre las manos al final del recorrido.',
  },
  {
    id: 'encogimientos-barra',
    name: 'Encogimientos con barra',
    alias: 'Barbell shrug',
    images: machineImagePair('encogimientos-barra'),
    category: 'brazos',
    muscles: ['Trapecio superior'],
    description:
      'Eleva los hombros hacia las orejas con los brazos extendidos, sin flexionar codos.',
  },
  {
    id: 'smith',
    machineNumber: '60',
    name: 'Smith',
    alias: 'Máquina Smith',
    images: machineImagePair('smith'),
    category: 'piernas',
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    description:
      'Barra guiada para sentadillas y otros movimientos de piernas con recorrido estable.',
  },
  {
    id: 'assisted-dip-chin',
    machineNumber: '61',
    name: 'Assisted dip/chin',
    alias: 'Dominadas y fondos asistidos',
    images: machineImagePair('assisted-dip-chin'),
    category: 'multifuncional',
    muscles: ['Dorsales', 'Bíceps', 'Pectorales', 'Tríceps'],
    description: 'El contrapeso facilita dominadas y fondos mientras desarrollas fuerza.',
    tracking: 'reps',
  },
  {
    id: 'dual-cable-cross',
    machineNumber: '62',
    name: 'Dual cable cross',
    alias: 'Polea doble ajustable',
    images: machineImagePair('dual-cable-cross'),
    category: 'multifuncional',
    muscles: ['Cuerpo completo'],
    description: 'Dos poleas regulables permiten empujes, jalones, curls y extensiones.',
  },
  {
    id: 'cable-crossover',
    machineNumber: '63',
    name: 'Cable crossover',
    alias: 'Cruce de poleas',
    images: machineImagePair('cable-crossover'),
    category: 'multifuncional',
    muscles: ['Pecho', 'Espalda', 'Hombros', 'Brazos', 'Glúteos'],
    description: 'Estación amplia de cables para entrenar distintos patrones y grupos musculares.',
  },
  {
    id: 'caminadora',
    name: 'Caminadora',
    alias: 'Treadmill',
    images: machineImagePair('caminadora'),
    category: 'cardio',
    muscles: ['Piernas', 'Glúteos', 'Sistema cardiovascular'],
    description: 'Permite caminar o correr ajustando velocidad e inclinación.',
    tracking: 'minutes',
  },
  {
    id: 'bicicleta-ergometrica',
    name: 'Bicicleta ergométrica',
    alias: 'Bicicleta vertical',
    images: machineImagePair('bicicleta-ergometrica'),
    category: 'cardio',
    muscles: ['Cuádriceps', 'Glúteos', 'Pantorrillas'],
    description: 'Cardio de bajo impacto con resistencia regulable desde el panel.',
    tracking: 'minutes',
  },
  {
    id: 'eliptica',
    name: 'Elíptica',
    alias: 'Cross-trainer',
    images: machineImagePair('eliptica'),
    category: 'cardio',
    muscles: ['Piernas', 'Glúteos', 'Brazos'],
    description: 'Movimiento continuo de cuerpo completo con bajo impacto articular.',
    tracking: 'minutes',
  },
  {
    id: 'remo-indoor',
    name: 'Remo indoor',
    alias: 'Remo ergométrico',
    images: machineImagePair('remo-indoor'),
    category: 'cardio',
    muscles: ['Espalda', 'Piernas', 'Core', 'Brazos'],
    description:
      'Combina empuje de piernas y jalón del torso en un ejercicio cardiovascular completo.',
    tracking: 'minutes',
  },
  {
    id: 'escaladora',
    name: 'Escaladora',
    alias: 'Stairmaster',
    images: machineImagePair('escaladora'),
    category: 'cardio',
    muscles: ['Piernas', 'Glúteos', 'Sistema cardiovascular'],
    description:
      'Sube escalones continuos manteniendo el torso erguido y sin colgarte de los apoyos.',
    tracking: 'minutes',
  },
  {
    id: 'bicicleta-reclinada',
    name: 'Bicicleta reclinada',
    alias: 'Recumbent bike',
    images: machineImagePair('bicicleta-reclinada'),
    category: 'cardio',
    muscles: ['Piernas', 'Glúteos', 'Sistema cardiovascular'],
    description:
      'Pedalea con la espalda apoyada en el respaldo; descarga la zona lumbar y las rodillas.',
    tracking: 'minutes',
  },
  {
    id: 'air-bike',
    name: 'Air bike',
    alias: 'Bicicleta de aire',
    images: machineImagePair('air-bike'),
    category: 'cardio',
    muscles: ['Piernas', 'Espalda', 'Brazos', 'Sistema cardiovascular'],
    description:
      'Pedalea y empuja las palancas a la vez; la resistencia del aire sube con tu propio ritmo.',
    tracking: 'minutes',
  },
];
